apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    devops-app: jenkins
  name: {{ required ".Values.roles.jenkins.serviceAccount" .Values.roles.jenkins.serviceAccount }}
  namespace: {{ required ".Values.projectName" .Values.projectName }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: jenkins
 namespace: {{ required ".Values.projectName" .Values.projectName }}
rules:
 - apiGroups: [""]
   resources: ["pods","configmaps","namespaces"]
   verbs: ["create","delete","get","list","patch","update","watch"]
 - apiGroups: [""]
   resources: ["pods/exec"]
   verbs: ["create","delete","get","list","patch","update","watch"]
 - apiGroups: [""]
   resources: ["pods/log"]
   verbs: ["get","list","watch"]
 - apiGroups: [""]
   resources: ["secrets"]
   verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: jenkins
 namespace: {{ required ".Values.projectName" .Values.projectName }}
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: jenkins
subjects:
 - kind: ServiceAccount
   name: {{ required ".Values.roles.jenkins.serviceAccount" .Values.roles.jenkins.serviceAccount }}
   namespace: {{ required ".Values.projectName" .Values.projectName }}